### ISSUE TITLE
bug: dueDate does not contain time.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#11]
**Describe the bug**
The `endDatePicker` contains a row for time too, the `DateFormatter` style is set to medium hence the time isn't stored in `endDate` variable.

**To Reproduce**
1. Go to TaskDetailsViewController
2. Click on endDateTextfield
3. Choose your endDate
4. See the text in the textfield.

**Expected behavior**
The endDate variable should have a different date-format.
eg: `01 Oct 2020 11:30 pm` should be the format

**Testing (please complete the following information):**
 - Simulator: iPhone 11
 - iOS: 13.7
 - Xcode: 11.7

**Additional context**
You can use DateFormatters `dateformat` property to fix this issue.
know more [here](https://developer.apple.com/documentation/foundation/dateformatter/1413514-dateformat)

**Comment by Monkeyank** [comment]
@aaryankotharii Fixed this in another PR!
