### ISSUE TITLE
DueDatePicker accepts past dates.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#18]
**Describe the bug**
The datepicker to pick due-date of the task accepts past dates.

**To Reproduce**
1. Create a task.
2. scroll to a past date in the picker.
3. click on add.

**Expected behavior**
The datePicker should only accept future dates!

**Additional context**
This can be fixed by using the minimum date property of the datePicker.
know more [here](https://developer.apple.com/documentation/uikit/uidatepicker/1615980-minimumdate)

**Comment by nikunjdk** [comment]
Can you assign this to me?
