### ISSUE TITLE
Feat: use core-data to store the ToDo list.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#21]
**Is your feature request related to a problem? Please describe.**
As of now, this app does not persist the data all my tasks are deleted as soon as the app closes. It would be great if my list is persisted and available to me everytime I open the application.

**Describe the solution you'd like**
This can be solved by the use of coreData.

**Additional context**
[FetchedResultsController](https://developer.apple.com/documentation/coredata/nsfetchedresultscontroller) shall be used to load/store/delete/edit the data as it can be seamlessly integrated with the tableview.

**Comment by tejuamirthi** [comment]
I'm taking up this issue as well. Will create seperate prs for different issues. I'll let you know in case I need any help.

**Comment by aaryankotharii** [comment]
Sure @tejuamirthi, once again you can refer [here](https://github.com/aaryankotharii/CoronaTracker) for reference.
Assigned.

**Comment by tejuamirthi** [comment]
Should I remove the task and label models(models.swift) file?

**Comment by aaryankotharii** [comment]
Surely, I hope you have created an entity based on the same model.
