### ISSUE TITLE
Feat: Add a searchBar to search tasks.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#22]
**Is your feature request related to a problem? Please describe.**
If I have a lot of tasks it gets difficult for me to scroll through the entire list and find a specific task. 

**Describe the solution you'd like**
A search bar under the navigation bar would be really helpful. So I can search for keywords and the list below filters accordingly.

**Comment by tejuamirthi** [comment]
I would like to take up this!

**Comment by aaryankotharii** [comment]
Hi @tejuamirthi , definitely, Thanks a lot for your interest in working on this issue!
Assigned.

**Comment by tejuamirthi** [comment]
Do you have any UI in mind? Or anything for referring for a look alike?

**Comment by aaryankotharii** [comment]
Yes, since this app completely based upon elements provided by UIKit, you shall use a search controller in the navigation item. if you are an iOS user, the UI will be same as your iPhones messages app or notes app.
refer [here](https://developer.apple.com/documentation/uikit/view_controllers/displaying_searchable_content_by_using_a_search_controller) for a sample project provided by apple.
you can also check this [repository](https://github.com/aaryankotharii/CoronaTracker) for implementing the same.
If you get stuck anywhere, feel free to comment and ill help you out!

**Comment by tejuamirthi** [comment]
We have to filter the data in a way that the text in search box matches with title and subtasks, right? Please let me know if it's only the title we need to match. @aaryankotharii

**Comment by aaryankotharii** [comment]
@tejuamirthi I reckon it would be a better user experience if we match the subtasks too. Either ways there is no right or wrong and entire implementation of #22 is totally up to you! 😃
