### ISSUE TITLE
Bug: star-task feature incomplete.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#27]
**Describe the bug**
The star task feature is incomplete hence clicking on star does not produce any result.

**To Reproduce**
1. Go to your tasks list.
2. Swipe left to see options.
3. click on star.

**Expected behavior**
Users should see which of their tasks are starred, the `isFavourite` property of a task should be true if it is starred and a star symbol should be seen on the corresponding task.

**Screenshots**
|Expected Output|
|-----------------|
| <img src = "https://user-images.githubusercontent.com/53724307/94842816-7525f180-0439-11eb-9199-51595e08de12.png" width = "300" > |

**Additional context**
SF symbols can be used for the star symbol. `star.fill`

**Comment by tejuamirthi** [comment]
Proceed with a new xib for the cell?

**Comment by er-aman-gupta** [comment]
Can i pick this up @aaryankotharii ?
