### ISSUE TITLE
Bug: Keyboard Tap to dismiss

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#28]
**Describe the bug**
in `TaskDetailsViewController` once the keyboard is up it does not dismiss under any circumstance.

**To Reproduce**
1. Go to Tasks list.
2. Click on `+` button.
3. Tap on `TaskTextField`
4. Now the keyboard cannot be dismissed

**Expected behavior**
The keyboard should dismiss when tapped anywhere on the view or when return key is pressed.

**Screenshots**
N/A

**Testing (please complete the following information):**
 - Device: iPhone 11
 - iOS: 14.0
 - Xcode 11.7

**Additional context**
you can refer [here](https://medium.com/@KaushElsewhere/how-to-dismiss-keyboard-in-a-view-controller-of-ios-3b1bfe973ad1) for all possible ways to solve this issue.

**Comment by Monkeyank** [comment]
@aaryankotharii Can I take this one?
