### ISSUE TITLE
Feat: Add an onboarding screen.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#29]
**Is your feature request related to a problem? Please describe.**
It would be great if the app had an onboarding screen like most application made by apple have.

**Describe the solution you'd like**
The screen should contain features of the app and corresponding icons to the feature. Onboarding screen should only be visible the first time a user opens the app.

**Additional context**
`userDefaults` can be used to keep track of wether app is opened or not.
Refer [HIG guidlines](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/onboarding/) for more.

**Comment by All3yp** [comment]
Hi, I would like to implement this onboarding🥺
Do I have to be a assigned to contribute? 😁

**Comment by aaryankotharii** [comment]
Hi @All3yp , firstly thank you for your interest in working on this issue. Yes, it is always preferred for a contributor to be assigned to an issue first, to avoid confusion among other contributors. That said, it seems like someone has already created a pr for this issue. You can comment on any other issue and I will assign it to you. You can always create your own issues too!
