### ISSUE TITLE
Bug: add validations for creating task.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#36]
**Describe the bug**
Creating tasks has no validations hence tasks can be created without a Title or without a dueDate

**To Reproduce**
1. Click `+`
2. empty the task title
3. click `Add`

**Expected behavior**
User should be alerted that the title is empty ( or the dueDate is empty ).

**Screenshots**
| expected outcome |
|--------------------|
| <img src = "https://user-images.githubusercontent.com/53724307/94934036-d3f67400-04e8-11eb-9996-7e624f0ff1b1.png" width = "300" >  |

**Additional context**
Use a UIAlertController to solve this issue.

**Comment by tejuamirthi** [comment]
I would like to take up this as well!

**Comment by aaryankotharii** [comment]
Hey @tejuamirthi this issue has been specifically marked as `good-first-issue` due to its simplicity. I will be adding new issues soon, you can pick them as you like. You can also create your own issues and I can assign them to you based on their feasibility.

**Comment by tejuamirthi** [comment]
sure @aaryankotharii . Thanks for pointing it out.

**Comment by mikaelacaron** [comment]
@aaryankotharii Is it required to be assigned to an issue before beginning to work on it? I would like to begin working on this, but I'm not sure if I'm allowed

**Comment by aaryankotharii** [comment]
Hi @mikaelacaron, firstly thank you for your interest on working on this issue. Yes, it is always preferred that a contributor is first assigned to an issue to avoid confusion among other contributors. That said, you are 100% allowed to work on this issue. We will be more than glad If you create more issues/prs on this repository.
Assigned.

**Comment by mikaelacaron** [comment]
Pull request #43 has been submitted.
