### ISSUE TITLE
Feat: Add tests target

### ISSUE THREAD

**Issue by rizwankce** [IEEE-VIT/ToDo-iOS#37]
**Is your feature request related to a problem? Please describe.**
It would be great and good practice to have unit tests

**Describe the solution you'd like**
Create a tests target to kick start adding tests when needed.

**Additional context**
Adding tests target can give us options to run tests on GitHub Actions CI whenever there is a PR raised

**Comment by rizwankce** [comment]
I would like to take this request if everyone is okay with it.

**Comment by aaryankotharii** [comment]
Hi @rizwankce, yes unit testing is an important part of any project. I would suggest you to add a few basic unit tests also along with the target you will be adding so new contributors can refer and add unit tests of their own for the new features they will be adding.
Assigned.
