### ISSUE TITLE
NavigationBarButton Title bug.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#4]
**Describe the bug**
The barButton title in `TaskDetailsViewController` is `Save` for both add Task and update Task, hence it is hard to distinguish the current operation for the user.

**To Reproduce**
1. Tap on `+` button in `TodoViewController`.
2. Add a new task.
3. Tap on your added task.
4. See topBarButton title.

**Expected behavior**
 It would be Better if the title is `Add` while adding a new task & `Update` while updating an existing task.

**Testing (please complete the following information):**
 - Simulator: iPhone 11
 - iOS: iOS 13.7
 - Xcode: 11.7

**Additional context**
the `task` variable in `TaskDetailsViewController` will determine wether operation is update or add. If the variable in `nil` it means the operation is `Add Task`.

**Comment by clarkeben** [comment]
@aaryankotharii happy to help with this 😀

**Comment by aaryankotharii** [comment]
Hey @clarkeben, This is does contain a pre-existing pr.
Feel free to pick any other issue and I will assign it to you!

**Comment by aaryankotharii** [comment]
fixed in #15
