### ISSUE TITLE
Add haptics.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#46]
**Is your feature request related to a problem? Please describe.**
As a user i would prefer some sort of haptic feedback upon any action I do in the app. for example a different haptic when I create a task, a different one for deleting a task, a haptic for alerts etc. 

**Describe the solution you'd like**
UIFeedbackGenerator can be used to create haptics on these instances.

**Describe alternatives you've considered**
N/A

**Additional context**
know more about UIFeedbackGenerator [here](https://developer.apple.com/documentation/uikit/uifeedbackgenerator)
refer [this](https://www.hackingwithswift.com/example-code/uikit/how-to-generate-haptic-feedback-with-uifeedbackgenerator) for all types of haptics that you can use.

**Comment by abraaolevi** [comment]
Hello @aaryankotharii! Could I work on this? 🙂

**Comment by aaryankotharii** [comment]
Hi @abraaolevi, this issue has been specifically marked as `good-first-issue` due to its simplicity, hence it would be a great issue to work on for first time contributors. You can comment under any other issue and I will assign it to you, also feel free to create your own issues!

**Comment by yabenatti** [comment]
Hi there! Since it's a good-first-issue, can I work on it?

**Comment by aaryankotharii** [comment]
sure! @yabenatti
Assigned.

**Comment by danglingP0inter** [comment]
@aaryankotharii Can you assign me this issue?

**Comment by aaryankotharii** [comment]
Hi @yabenatti, Will you be working on this issue or shall we assign it to someone else?

**Comment by yabenatti** [comment]
Yes! I'm working on it. Will push something tomorrow

**Comment by aaryankotharii** [comment]
alright no issues, just wanted to confirm.
