### ISSUE TITLE
Tasks history

### ISSUE THREAD

**Issue by lucasca73** [IEEE-VIT/ToDo-iOS#47]
## Feature request

**Describe the solution you'd like**
A place to see completed tasks, a TabBar at the bottom with two tabs, Tasks and History.

**Comment by mikaelacaron** [comment]
@aaryankotharii I would do this! However I think the issue should be changed. First I'd have to implement completing a task (I'm thinking a right swipe action on the cell)

After that a tab view controller to have a Tasks and History tab.

**Comment by aaryankotharii** [comment]
yes! @mikaelacaron it would be great if you could create a pull request, draft it and explain your plan there. Once you've implemented the whole idea, I will review the pr then.
Assigned.
