### ISSUE TITLE
Task image Attachment

### ISSUE THREAD

**Issue by lucasca73** [IEEE-VIT/ToDo-iOS#48]
## Feature request

**Describe the solution you'd like**
When creating or editting a task, an option to add images from the library or camera.

**Comment by aaryankotharii** [comment]
Hey @lucasca73 , that is a great feature! Shall I assign you to this issue?

**Comment by lucasca73** [comment]
hell yeah ;D thanks bud, glad to contribute

**Comment by aaryankotharii** [comment]
Assigned.
