### ISSUE TITLE
Empty states for no tasks added after launch and no result found while searching task.

### ISSUE THREAD

**Issue by Harsh061** [IEEE-VIT/ToDo-iOS#51]
**Description / Suggestion**

1. When ever we launch the application first time after installation we see a blank screen. Ideally there should be a text suggesting "No tasks added" or something descriptive rather than blank white screen.
2. Also when launching the app for the first time, and no task is added yet, we see filter option in the navigation bar. Just a suggestion. It should only be displayed when any task is present. Else it should be hidden.
3. While searching if search results are not found then also we should display "No search results found" or something descriptive rather than blank screen. 

**Solution**
1. A simple label which will be displayed in case no task is present in our core data. 
2. Ternary operator which will hide and show filter option based on tasks count. 
3. A simple label which will be displayed only in case no results are found.

**Comment by aaryankotharii** [comment]
Hi @Harsh061 , Thank you for creating this issue! I would recommend you to create three separate issues for all three points stated above.

**Comment by Harsh061** [comment]
Sure @aaryankotharii . Meanwhile can I close this issue and create three new ?

**Comment by aaryankotharii** [comment]
Yes @Harsh061 sure!

**Comment by Harsh061** [comment]
Creating separate issues and closing this.
