### ISSUE TITLE
Empty state after launch when no task is added

### ISSUE THREAD

**Issue by Harsh061** [IEEE-VIT/ToDo-iOS#55]
**Description**
When ever we launch the application first time after installation we see a blank screen. Ideally there should be a text suggesting "No tasks added" or something descriptive rather than blank white screen.

**Solution**
A simple label which will be displayed in case no task is present in our core data.

**Comment by Drag0ndust** [comment]
I can take over this task

**Comment by aaryankotharii** [comment]
Great @Drag0ndust ! Thank you for your interest on working on this issue.
Assigned.

**Comment by Drag0ndust** [comment]
@aaryankotharii PR is ready ;)
