### ISSUE TITLE
Display zero state for no search results found

### ISSUE THREAD

**Issue by Harsh061** [IEEE-VIT/ToDo-iOS#57]
**Description**
While searching if search results are not found then we should display "No search results found" or something descriptive rather than blank screen.

**Solution**
A simple label which will be displayed only in case no results are found.

**Comment by aaryankotharii** [comment]
Hi @Harsh061 thank you for creating this issue.
would you like to work on this issue or shall we keep it open for  new contributors?

**Comment by Harsh061** [comment]
@aaryankotharii  I can work on this. But it would be great if more people contribute to this project. For now you can keep it open for new contributors.

**Comment by aaryankotharii** [comment]
sure!

**Comment by Guiguerreiro39** [comment]
Hello
I can tackle this issue if that's ok and, hopefully, be able to work on more issues to come!

**Comment by tno1337** [comment]
@Harsh061 thank you for letting this issue open. I would like to use this as my first PR to Hacktoberfest or any open source project. 
And thanks to @aaryankotharii for this project to contribute!

**Comment by aaryankotharii** [comment]
Great @NiklasOemler! Thank your interest in working on this issue.
You can feel free to open new issues and request to work on any!
