### ISSUE TITLE
Feat: Sorting Tasks.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#6]
**Is your feature request related to a problem? Please describe.**
As a user I would prefer to have sorting options for my task list. For example sort by due-Date or sort alphabetically.

**Describe the solution you'd like**
A `barButtonItem` for sort can be added to the `navigationBar` in `TodoViewController`.
Tapping on this button would bring up an actionSheet with different options to sort.

**Additional context**
Sample code [here](https://developer.apple.com/documentation/uikit/windows_and_screens/getting_the_user_s_attention_with_alerts_and_action_sheets) can be referred to create UIAlertController of type actionSheet

**Comment by er-aman-gupta** [comment]
@aaryankotharii  Can i pick this up?

**Comment by aaryankotharii** [comment]
Sure @er-aman-gupta , thank you for your interest in working on this issue!
Assigned.

**Comment by er-aman-gupta** [comment]
@aaryankotharii, can u pls add me as contributer to project, i'm getting permission denied error.
