### ISSUE TITLE
Hide tabbar on segue.

### ISSUE THREAD

**Issue by aaryankotharii** [IEEE-VIT/ToDo-iOS#69]
**Describe the bug**
when user taps on `+` to add a task, the tabbar is still present on the bottom which is not required and blocks bottom of the screen.

**To Reproduce**
1. Go to todoViewcontroller
2. Tap on +
3. See bug.

**Expected behavior**
the tabbar should be hidden when TaskDetailsViewController is presented

**Screenshots**
<img src = "https://user-images.githubusercontent.com/53724307/95671712-c8294280-0bb7-11eb-8efa-1f0a824adf8c.png" width = "300">

**Testing (please complete the following information):**
 - Device: iPhone 11
 - iOS: 14.0
 - Xcode 12.0

**Additional context**
refer [here](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621863-hidesbottombarwhenpushed)

**Comment by gsnsg** [comment]
@aaryankotharii  Can I work on this issue ? I have a working solution

**Comment by aaryankotharii** [comment]
sure @gsnsg, thank you for your interest in working on this issue!
Assigned.

**Comment by gsnsg** [comment]
@aaryankotharii  Please review my PR #73

**Comment by gsnsg** [comment]
Hi, @aaryankotharii  I have changed the code and now it works as intended. Please review my PR #74
