### ISSUE TITLE
Delete tasks on the History Tab

### ISSUE THREAD

**Issue by mikaelacaron** [IEEE-VIT/ToDo-iOS#70]
**Is your feature request related to a problem? Please describe.**
Feature Request: Be able to delete tasks from the History tab

**Describe the solution you'd like**
Trailing swipe action to delete tasks on the History tab.

**Describe alternatives you've considered**
Or long press on a task and an action sheet comes up and confirm to delete the task

**Comment by aaryankotharii** [comment]
Thats a great idea @mikaelacaron, I would suggest to use right swipe for delete and show an action sheet to confirm delete action. I am avoiding long press as we will be adding context menus to the tableview soon!
Assigned.

**Comment by mikaelacaron** [comment]
@aaryankotharii  You mean the trailing swipe action?

**Comment by aaryankotharii** [comment]
yes.
