### ISSUE TITLE
New unit tests for marking a task as complete

### ISSUE THREAD

**Issue by mikaelacaron** [IEEE-VIT/ToDo-iOS#71]
**Is your feature request related to a problem? Please describe.**
Code feature, add unit tests to confirm that marking a task as complete always works

**Describe the solution you'd like**
Create unit tests

**Describe alternatives you've considered**
N/A

**Comment by aaryankotharii** [comment]
Hi @mikaelacaron , thank you for submitting this issue.
Would you like to work on this issue or shall we keep it open for other contributors?

**Comment by mikaelacaron** [comment]
@aaryankotharii Other contributors are welcome!

**Comment by Recouse** [comment]
Hi,
I've made a pull request, you can check it and assign me to this issue.
