### ISSUE TITLE
Empty State Shows on History Tab When It Shouldn't

### ISSUE THREAD

**Issue by mikaelacaron** [IEEE-VIT/ToDo-iOS#80]
**Describe the bug**
The Empty state of the History tab shows whether or not there's a task there or not. It's not checking for no completed items.

**To Reproduce**
1. Go to the Tasks tab
2. Create a new task
3. Use the leading swipe action to complete the task
4. Go to the History tab
5. The Empty state "no task history found"is still showing, when it shouldn't because there is a completed task

**Expected behavior**
The empty state shouldn't be shown once there is a task on the history page

**Screenshots**
<img width="383" alt="Screen Shot 2020-10-16 at 8 51 43 PM" src="https://user-images.githubusercontent.com/22946902/96324769-6cb0e780-0ff1-11eb-81f7-d605e2dcbe56.png">

**Testing (please complete the following information):**
 - Device: iPhone 11 Simulator
 - iOS: 14.0
 - Xcode 12.0.1

**Additional context**
In viewWillAppear `setupEmptyState` but no check is occurring to ensure there are no tasks on this tab

**Comment by mikaelacaron** [comment]
@aaryankotharii I am open to anyone completing this. This would be a good first issue!

**Comment by danglingP0inter** [comment]
@mikaelacaron please assign this to me.

**Comment by aaryankotharii** [comment]
Hi @danglingP0inter, thank you for your interest in working on this issue!
Assigned.

**Comment by aaryankotharii** [comment]
fixed in #81
