### ISSUE TITLE
Whitespace Is being accepted as Task name and subtask name while it shouldn't

### ISSUE THREAD

**Issue by danglingP0inter** [IEEE-VIT/ToDo-iOS#82]
**Describe the bug**
Entering only a whitespace in task or subtasks textfield under task tab is getting accepted

**To Reproduce**
1. Go to Tasks
2. Click on '+' button on top-right corner to add a task
3. Input whitespace/s in task and/or subtask textfield. Input end date
4. Add task.

**Expected behavior**
Task name should've leading and trailing spaces trimmed. Hence, a alert should've shown saying task name/subtask name is empty or Invalid.

**Testing:**
 - Device: iPhone11 Pro max
 - iOS: 13.3
 - Xcode 11.3.1

**Comment by aaryankotharii** [comment]
Hi @danglingP0inter, Thank you for submitting this issue!
Assigned.

**Comment by pastre** [comment]
I'd love to solve this, as a part of Hacktoberfest xD

**Comment by aaryankotharii** [comment]
fixed in #84
