### ISSUE TITLE
Task bar image missing

### ISSUE THREAD

**Issue by danglingP0inter** [IEEE-VIT/ToDo-iOS#85]
**Describe the bug**
No image for task in tab bar.

**Expected behavior**
An image for task should be there. 

**Testing (please complete the following information):**
 - Device: iPhone7
 - iOS: 13.3
 - Xcode 11.3.1

**Comment by danglingP0inter** [comment]
@aaryankotharii please assign this to me.

**Comment by aaryankotharii** [comment]
fixed in #86 by @danglingP0inter.
