### ISSUE TITLE
Button at List is not working on History tab

### ISSUE THREAD

**Issue by SeungJunLee-Apple** [IEEE-VIT/ToDo-iOS#90]
I think your app may have tried to show the title of the Task, subtitle of the task, and image attached to it when the user clicks the button next to the task title. But on the history tab tapping the button doesn't direct to the new View as it does on the Task tab. Could you check this?

**To Reproduce**
1. Create a new task at Tasks Tab
2. Mark the task as completed by swiping it left
3. Go to History Tab and click the button next to the task title
4. Clicking the button doesn't direct to the new View as it does on the Task tab

**Tested on**
 - Device: [iPhone 11 Pro]
 - iOS: [14.1]
 - Xcode [12.1]

**Comment by markk628** [comment]
Hey 이성준님 mind if I take a look at this?

**Comment by aaryankotharii** [comment]
closed with #91
